---
sudo: false
cache: bundler

language: ruby
rvm:
  - 2.1.5

services: mysql

before_script:
  - cp spec/ci/database.mysql.yml config/database.yml;
  - bundle exec rake app:db:create
  - bundle exec rake app:db:migrate


script:
  - bundle exec rake app:spec

branches:
  only:
    - master

notifications:
  slack: trustarts:FrVc7H8dDadhctfZ7NvHTZES
